import logging
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from typing import Dict, Any
import sqlite3
import json

from app.core_logic import inspect_agent_output

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("semantic-dlp")

app = FastAPI(
    title="Aegis Semantic Data Exfiltration Detector",
    description="Identifies when an agent's outputs are carrying sensitive information in non-standard form.",
    version="1.0.0",
)

# Initialize Audit Log Database
def init_db():
    conn = sqlite3.connect("audit_logs.db")
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS audit_logs
                 (timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                  agent_id TEXT, decision TEXT, details TEXT)''')
    conn.commit()
    conn.close()

init_db()

def log_to_db(agent_id, decision, details):
    conn = sqlite3.connect("audit_logs.db")
    c = conn.cursor()
    c.execute("INSERT INTO audit_logs (agent_id, decision, details) VALUES (?, ?, ?)",
              (agent_id, decision, json.dumps(details)))
    conn.commit()
    conn.close()

class InspectRequest(BaseModel):
    agent_id: str = Field(..., description="ID of the AI agent generating the text")
    output_text: str = Field(..., description="The text generated by the agent to be inspected")

class InspectResponse(BaseModel):
    decision: str
    details: Dict[str, Any]

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    logger.error(f"Unhandled exception during request processing: {str(exc)}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"decision": "ERROR", "message": "An internal server error occurred during inspection."}
    )

@app.get("/health")
def health_check():
    """Basic health check endpoint"""
    return {"status": "ok", "service": "semantic-dlp"}

@app.post("/api/v1/inspect", response_model=InspectResponse)
def inspect_endpoint(payload: InspectRequest):
    """
    Inspect an AI agent's output for semantic exfiltration of protected facts.
    """
    logger.info(f"Received inspect request for agent_id={payload.agent_id}")
    try:
        result = inspect_agent_output(payload.output_text)
        
        decision = result.get("decision", "ERROR")
        logger.info(f"Inspection complete for agent_id={payload.agent_id}. Decision: {decision}")
        log_to_db(payload.agent_id, decision, result)
        
        return InspectResponse(
            decision=decision,
            details=result
        )
    except Exception as e:
        logger.error(f"Error during semantic inspection: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))